data_frame = data_frame.interpolate()
    # print(__print_data(data_frame))
    # time.sleep(2)
    # __handle_duplicated_rows(data_frame, remove)
    # #__noise_cnacletion(data_frame, remove)    
    # __missing_values_cnacletion(data_frame, remove)